--- 
title: "Research Module in Econometrics & Statistics"
author: "Prof. Dominik Liebl (dliebl@uni-bonn.de) and Christopher Walsh (cwalsh@uni-bonn.de)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: lidom/RM_ES_Script
url: 'http\://dliebl.com/RM_ES_Script/'
description: "Script for the research module in econometrics & statistics (University Bonn)."
---

# Preface {-}


This is the script for the research module in econometrics & statistics. 


Repo that makes this site: https://github.com/lidom/RM_ES_Script


**Research Module in Econometrics and Statistics** 

**Description:**

*Lecture-Phase:* The lecture-phase of this research module is intended to introduce the students to fundamental concepts of (applied and mathematical) statistics, as well as, to provide the students with reasoning skills for communicating statistical results. Participation in the lecture-phase is strongly recommended and active participation is desirable. 

*Project-Phase:* The students have the opportunity to choose among a set of specific projects. Topics suggested by the students are generally appreciated, but will be assessed with respect to their feasibility. Each project must focus on one specific statistical method/topic (for instance, panel data analysis, clustered standard errors, non-parametric regression, etc.) and should contain the following three parts:

  1. A critical description of the statistical method and its theoretical properties 
  2. Monte Carlo simulation studies to assess the finite sample properties of the statistical method
  3. One or more real-data applications to showcase the practical use of the statistical/econometric method. 

Depending on the actual number of participants, it might be that the project work has to be carried out as a group task rather than as an individual task.

*Software:* Due to the mathematical contents, it is strongly recommended to use LaTeX for preparing the presentation slides and the term papers. Moreover, the Monte Carlo simulations and the real-data applications will make it necessary to work with advanced software such as R, Python, or Matlab. Short introductions to LaTeX and R will be given during the lecture-phase, but the students should be willing to work with such software. 

**Grading:** The final grade will be a weighted average of the presentation (40%) and the  research paper (60%).

**Registration:** You need to register for this course via [BASIS](https://basis.uni-bonn.de/). 

**Registration period:**  Oct. 12-19. (**Caution:** No timely registration means you cannot participate in this course)   


\


**Time Table:**

Date        Time               Topics$^*$
----------  -----------------  ---------------------------------
12.10.      14:15 - 15:45      General Introduction / Introduction to R / Topic Choices [Liebl/Walsh]
13.10.      14:15 - 15:45      Introduction to R (Flipped Classroom) / Topic Choices [Liebl/Walsh]
19.10.      14:15 - 15:45      Estimation Theory [Walsh]
20.10.      14:15 - 15:45      Estimation Theory [Walsh]
26.10.      14:15 - 15:45      Regression / Monte-Carlo Simulations (Flipped Classroom) [Walsh]
27.10.      14:15 - 15:45      Test Theory [Liebl]
02.11.      14:15 - 15:45      Test Theory [Liebl]
03.11.      14:15 - 15:45      Monte-Carlo Simulations  (Flipped Classroom) [Liebl]
09.11.      14:15 - 15:45      How to Write and Present [Walsh]
18.01.      14:15 - 15:45      Presentations [Liebl/Walsh]
19.01.      14:15 - 15:45      Presentations [Liebl/Walsh]

$^*$ This is just the approximate general structure. Depending on your pre-knowledge, we may deviate from this.


- **Virtual Lecture-Room (Zoom):** [Zoom-Meeting Link](https://uni-bonn.zoom.us/j/91400665510?pwd=RUl5NW9mMjcyQlk2VkRGbXFrSmJlQT09) \
Meeting-ID: 914 0066 5510\
Password: 544848

- **Supervision meetings:** From Nov. to Jan. 
- **Scheduling of appointments:** [HERE](https://docs.google.com/spreadsheets/d/1clb0ple3GaRlwod5JOKK84A996p1BKNMSs32JrqBZ_A/edit?usp=sharing)


\


**Presentations:**

* For groups of 1-2: 15-25 minutes
* For groups of   3: 20-25 minutes


\


**Term Paper:**

* Every term paper should consist of the following parts:
    * Introduction of the general problem and a short overview about the relevant literature.
    * Description of the considered method(s).
    * Assessment of the method(s) by means of Monte-Carlo simulations.
    * Application to real data.
* Page Count:
    * For groups of 1-2: 10-15 pages (plus bibliography and appendix)
    * For groups of 3: 15-20 pages (plus bibliography and appendix)
    * Long tables, proofs, additional figures, etc. should be placed in the appendix.
    * Line-spacing: 1.5
    
* **Deadline for submission of slides:** Jan. 17, 2022, via e-mail to [dliebl@uni-bonn.de](mailto:dliebl@uni-bonn.de)    
* **Deadline for submission of term papers:** Feb. 11, 2022, via e-mail to [dliebl@uni-bonn.de](mailto:dliebl@uni-bonn.de)





